---
- name: Check Certificates on port
  hosts: all

  roles:
    - shadowman_cert_check

  tasks:

    - name: Build the report
      ansible.builtin.include_role:
        name: build_report_certs
        apply:
          delegate_to: report.shadowman.dev
          run_once: true
