---
- name: Controller Changes
  hosts: localhost
  gather_facts: false

  tasks:

    - name: Get Current Job information
      ansible.builtin.uri:
        url: https://{{ lookup('env', 'CONTROLLER_HOST') }}/api/v2/jobs/{{ awx_job_id }}/
        user: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
        password: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
        force_basic_auth: true
        method: "GET"
        status_code: "200"
        validate_certs: false
      register: job_details

    - name: Set job inventory details
      ansible.builtin.set_fact:
        picked_inventory: "{{ job_details.json.summary_fields.inventory.name }}"

    - name: Set job credential details
      ansible.builtin.set_fact:
        picked_credential: "{{ item.name }}"
      when: item.kind == 'ssh'
      loop: "{{ job_details.json.summary_fields.credentials }}"

    - name: Debug results
      ansible.builtin.debug:
        msg: "{{ picked_credential }} and {{ picked_inventory }}"
