---
- name: Get VMWare tag info
  community.vmware.vmware_vm_info:
    validate_certs: false
    show_tag: true
    vm_type: "vm"
  register: vmware_info

- name: Get Azure VM Info
  azure.azcollection.azure_rm_virtualmachine_info:
    tags:
      - owner
  register: azure_info

- name: Block for RHV
  block:
  - name: Login to RHV
    redhat.rhv.ovirt_auth:
      hostname: "{{ rhvm_fqdn }}"
      username: "{{ rhvm_user }}"
      password: "{{ rhvm_password }}"
      ca_file: "{{ rhvm_cafile | default(omit) }}"
      insecure: "{{ rhvm_insecure | default(true) }}"  

  - name: Get RHV VM info
    redhat.rhv.ovirt_vm_info:
      auth: "{{ ovirt_auth }}"
      follow:
        - tags
    register: rhv_info

  always:
    - name: Logout from RHV
      redhat.rhv.ovirt_auth:
        state: absent
        ovirt_auth: "{{ ovirt_auth }}"
