---
- name: Get VMWare tag info
  community.vmware.vmware_vm_info:
    validate_certs: false
    show_tag: true
    vm_type: "vm"
  register: vmware_info

- name: Get Azure VM Info
  azure.azcollection.azure_rm_virtualmachine_info:
    tags:
      - owner
  register: azurevms
