---
- name: Scan Linux
  ansible.builtin.include_tasks: linux.yml
  when: ansible_os_family != "Windows"

- name: Scan Windows
  ansible.builtin.include_tasks: windows.yml
  when: ansible_os_family == "Windows"
