---
- name: Create site directory structure
  ansible.windows.win_file:
    path: "{{ report_path }}"
    state: directory

- name: Get AD user accounts with groups and lock status
  ansible.windows.win_shell: |
    Import-Module ActiveDirectory
    Get-ADUser -Filter * -Property GivenName, Surname, SamAccountName, MemberOf, LockedOut |
    Select-Object GivenName, Surname, SamAccountName, @{Name="Groups";Expression={(Get-ADUser -Identity $_.SamAccountName -Property MemberOf |
    Select-Object -ExpandProperty MemberOf | Get-ADGroup | Select-Object -ExpandProperty Name) -join ", "}}, LockedOut |
    ConvertTo-Json
  register: ad_users

- name: Create HTML file from template
  ansible.windows.win_template:
    src: templates/users_template.html.j2
    dest: C:\Inetpub\wwwroot\user_info.html
  vars:
    users: "{{ ad_users.stdout | from_json }}"

- name: Ensure IIS is installed
  block:
    - name: Install IIS
      ansible.windows.win_feature:
        name: Web-Server
        state: present
      notify: IIS_running
  rescue:
    - name: Retry iis due to WINRM issues
      ansible.windows.win_feature:
        name: Web-Server
        state: present
      notify: IIS_running

- name: Ensure Default Site is removed
  block:
    - name: Remove Default Site
      community.windows.win_iis_website:
        name: Default Web Site
        state: absent
  rescue:
    - name: Remove Default Site again due to WINRM
      community.windows.win_iis_website:
        name: Default Web Site
        state: absent

- name: Configure site
  block:
    - name: Configure site
      community.windows.win_iis_website:
        name: Ansible Tower
        physical_path: C:\inetpub\wwwroot
        state: started
        port: 80
        ssl: true
      notify: IIS_running
  rescue:
    - name: Configure site twice due to WinRM
      community.windows.win_iis_website:
        name: Ansible Tower
        physical_path: C:\inetpub\wwwroot
        state: started
        port: 80
        ssl: true
      notify: IIS_running

- name: Copy Cert
  block:
    - name: Copy Cert
      ansible.windows.win_copy:
        src: /certs/certificate.pfx
        dest: C:\Inetpub\wwwroot\web_certificate.pfx
  rescue:
    - name: Retry Copy Cert due to WINRM issues
      ansible.windows.win_copy:
        src: /certs/certificate.pfx
        dest: C:\Inetpub\wwwroot\web_certificate.pfx

- name: Install Cert
  block:
    - name: Install certificate
      ansible.windows.win_certificate_store:
        path: C:\Inetpub\wwwroot\web_certificate.pfx
        file_type: pkcs12
        state: present
        password: "{{ windowspassword }}"
        store_location: LocalMachine
        key_storage: machine
      register: thumbprint
  rescue:
    - name: Install certificate twice due to WinRM
      ansible.windows.win_certificate_store:
        path: C:\Inetpub\wwwroot\web_certificate.pfx
        file_type: pkcs12
        state: present
        password: "{{ windowspassword }}"
        store_location: LocalMachine
        key_storage: machine
      register: thumbprint

- name: Configure bindings
  block:
    - name: Configure site bindings
      community.windows.win_iis_webbinding:
        name: Ansible Tower
        port: "443"
        protocol: https
        certificate_hash: "{{ thumbprint.thumbprints[0] }}"
        state: present
      notify: IIS_running
  rescue:
    - name: Configure site bindings twice due to WINRM issues
      community.windows.win_iis_webbinding:
        name: Ansible Tower
        port: "443"
        protocol: https
        certificate_hash: "{{ thumbprint.thumbprints[0] }}"
        state: present
      notify: IIS_running
