---
- name: Create/Update/Remove User in AD
  microsoft.ad.user:
    firstname: "{{ first_name }}"
    surname: "{{ last_name }}"
    name: "{{ username }}"
    password: "{{ password }}"
    groups:
      set:
        - Domain Admins
    state: "{{ state }}"
    update_password: on_create
    domain_username: "{{ domainuser }}"
    domain_password: "{{ domainpassword }}"
