---
- name: Add Windows host to AD
  microsoft.ad.membership:
    dns_domain_name: ad.shadowman.dev
    hostname: "{{ fqdn.split('.')[0] }}"
    domain_admin_user: "{{ domainuser }}"
    domain_admin_password: "{{ domainpassword }}"
    state: domain
    reboot: true
