---
- name: Remove old kernels RHEL 7 and older
  ansible.builtin.command: package-cleanup --oldkernels -y
  when: ansible_pkg_mgr == "yum"
  register: kernelresult
  changed_when: (kernelresult.stdout_lines | last) == "Complete!"
  failed_when: kernelresult.rc > 1

- name: Perform yum clean
  ansible.builtin.command: yum clean all
  when: ansible_pkg_mgr == "yum"
  register: yumresult
  changed_when: yumresult.rc == 0
  failed_when: yumresult.rc > 1

- name: Remove old kernels RHEL 8 and newer
  ansible.builtin.command: dnf remove --oldinstallonly -y
  when: ansible_pkg_mgr == "dnf"
  register: kerneldnfresult
  changed_when: kerneldnfresult.rc == 0
  failed_when: kerneldnfresult.rc > 1

- name: Perform dnf clean
  ansible.builtin.command: dnf clean all
  when: ansible_pkg_mgr == "dnf"
  register: dnfresult
  changed_when: dnfresult.rc == 0
  failed_when: dnfresult.rc > 1
