---
- name: SELinux permissive
  ansible.builtin.command:
    cmd: setenforce permissive

- name: Start Podman service
  ansible.builtin.command:
    cmd: systemctl start podman

- name: Start podman containers
  ansible.builtin.command:
    cmd: podman start conjur_client nginx_proxy conjur_server postgres_database 87f8ba3ea251-infra
